service: bucketlist
frameworkVersion: '3'

custom:
  serverless-offline:
    httpPort: 3000 # 로컬 포트
    lambdaPort: 3001 # 람다 포트

provider:
  name: aws
  stage: bucket
  runtime: nodejs16.x # 서버 버전
  region: ap-northeast-2

functions:
  api:
    handler: src/app.index

    events:
      - http:
          path: /api/main/test
          method: get

plugins:
  - serverless-offline
