service: bucketlist
frameworkVersion: "3"

custom:
  serverless-offline:
    httpPort: 3000 # 로컬 포트
    lambdaPort: 3001 # 람다 포트

provider:
  name: aws
  stage: bucket
  runtime: nodejs16.x # 서버 버전
  region: ap-northeast-2

functions:
  api:
    handler: src/app.index

    events:
      - http:
          path: /api/auth/join
          method: post
          cors: true

      - http:
          path: /api/auth/login
          method: post
          cors:
            origin: http://localhost:8080
            allowCredentials: true

      - http:
          path: /api/main/bucklist/{categoryID}
          method: get
          cors:
            origin: http://localhost:8080
            allowCredentials: true

      - http:
          path: /api/main/bucklist/{bucketlistID}
          method: delete
          cors:
            origin: http://localhost:8080
            allowCredentials: true

      - http:
          path: /api/main/bucklist
          method: post
          cors:
            origin: http://localhost:8080
            allowCredentials: true

      - http:
          path: /api/category
          method: get
          cors: true

      - http:
          path: /api/token/refresh-token
          method: post
          cors:
            origin: http://localhost:8080
            allowCredentials: true

      - http:
          path: /api/token/verify/refresh-token
          method: post
          cors:
            origin: http://localhost:8080
            allowCredentials: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
